version: '3.8'
services:
  web:
    build: .
    command: python /books/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/books
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-&du1sjwtigfcs9z=+1*qnrv2vi*n5#z(7ky2fwqe@tiwm%1c6j"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: