# Generated by Django 3.2 on 2023-04-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')], 'verbose_name': 'Книгу', 'verbose_name_plural': 'Книги'},
        ),
    ]
